spring:
  application:
    name: team3_toyproject
  datasource:
    url: jdbc:mysql://localhost:3306/team3_toyproject
    username: root
    password: 25467600sd!M
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # (create, update, validate, none)
    show-sql: true
